# Generated by Django 6.0.5 on 2026-05-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.skill', verbose_name='Навыки'),
        ),
    ]
